#!/usr/bin/env python3
"""Convert CASE19 metrics JSON into report-safe LaTeX macros."""

from __future__ import annotations

from report_language import report_text

import json
from pathlib import Path

CASE_DIR = Path(__file__).resolve().parents[1]
METRICS_PATH = CASE_DIR / "outputs" / "metrics.json"
MACROS_PATH = CASE_DIR / "report" / "metrics_macros.tex"


def latex(value: object) -> str:
    if value is None:
        return "--"
    text = f"{value:.6g}" if isinstance(value, float) else str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "_": r"\_",
        "#": r"\#",
        "$": r"\$",
        "{": r"\{",
        "}": r"\}",
    }
    escaped = "".join(replacements.get(character, character) for character in text)
    return escaped.replace("<=", r"\ensuremath{\le}").replace(">=", r"\ensuremath{\ge}")


def main() -> None:
    if METRICS_PATH.exists():
        payload = json.loads(METRICS_PATH.read_text(encoding="utf-8"))
    else:
        payload = {
            "overall_status": "NOT EVALUABLE",
            "reason": "outputs/metrics.json does not exist",
            "metrics": [],
        }
    metrics = payload.get("metrics", [])
    rows = []
    for metric in metrics:
        expected = latex(metric.get("expected"))
        if metric.get("tolerance"):
            expected += " (" + latex(metric["tolerance"]) + ")"
        rows.append(
            f"{latex(metric.get('name'))} & {expected} & "
            f"{latex(metric.get('calculated'))} {latex(metric.get('units', ''))} & "
            f"{latex(metric.get('status', 'NOT EVALUABLE'))} \\\\"
        )
    if not rows:
        rows = [f"{latex(payload.get('reason', 'No calculated metrics are available'))} & -- & -- & NOT EVALUABLE \\\\"]

    status = payload.get("overall_status", "NOT EVALUABLE")
    if status in {"NOT RUN", "INCOMPLETE", "BLOCKED"}:
        status = "NOT EVALUABLE"
    body = [
        "% Generated by scripts/metrics_to_macro.py; do not edit by hand.",
        rf"\newcommand{{\VerificationStatus}}{{{latex(status)}}}",
        rf"\newcommand{{\VariantCount}}{{{int(payload.get('required_outputs_complete', False))}}}",
        rf"\newcommand{{\MetricCount}}{{{len(metrics)}}}",
        rf"\newcommand{{\PassingMetricCount}}{{{sum(m.get('status') == 'PASS' for m in metrics)}}}",
        "\\newcommand{\\MetricRows}{%",
        *rows,
        "}",
        "",
    ]
    MACROS_PATH.write_text(report_text("\n".join(body)), encoding="utf-8")
    print(f"[OK] wrote {MACROS_PATH}")


if __name__ == "__main__":
    main()

