#!/usr/bin/env python3
"""Remove regenerable suite artifacts with two explicit cleanup levels.

Run without ``--apply`` to preview the cleanup.  Figures, result JSON, generated
report inputs, and compiled PDFs are retained so reports can be rebuilt without
rerunning ELMFIRE during the normal cleanup.  ``--prepare-run`` additionally
invalidates those prior evaluation and report products before a new suite run.
"""

from __future__ import annotations

import argparse
import os
import shutil
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
GENERATED_DIRECTORIES = (
    ROOT_DIR / "output",
    ROOT_DIR / "tmp",
)
LATEX_SUFFIXES = (
    ".aux",
    ".fdb_latexmk",
    ".fls",
    ".log",
    ".out",
    ".synctex.gz",
    ".toc",
)
CASE_RUNTIME_DIRECTORY_NAMES = frozenset({"logs", "outputs", "scratch"})
GENERATED_CASE_REPORT_FILES = frozenset(
    {
        "latexmk.stderr",
        "latexmk.stdout",
    }
)
PREPARE_RUN_CASE_REPORT_FILES = frozenset(
    {
        "case_report.pdf",
        "metrics_macros.tex",
    }
)
AGGREGATE_REPORT_FILES = frozenset(
    {
        "validation_report.pdf",
        "verification_report.pdf",
    }
)
REPORT_SUPPORT_OUTPUT_SUFFIXES = frozenset({".json"})


def is_report_path(path: Path) -> bool:
    relative = path.relative_to(ROOT_DIR)
    return relative.parts[0] == "main_report" or "report" in relative.parts


def is_active_case_path(path: Path) -> bool:
    """Return whether *path* belongs to an active verification/validation tree."""
    relative = path.relative_to(ROOT_DIR)
    return (
        len(relative.parts) >= 2
        and relative.parts[0] == "cases"
        and relative.parts[1] in {"Verification", "Validation"}
        and "__legacy__" not in relative.parts
    )


def is_generated_report_file(path: Path, prepare_run: bool = False) -> bool:
    """Identify case-report products that case pipelines regenerate."""
    relative = path.relative_to(ROOT_DIR)
    generated_names = GENERATED_CASE_REPORT_FILES
    if prepare_run:
        generated_names = generated_names | PREPARE_RUN_CASE_REPORT_FILES
    return (
        is_active_case_path(path)
        and "report" in relative.parts
        and path.name in generated_names
    )


def is_aggregate_report_file(path: Path) -> bool:
    """Identify the two compiled suite guides."""
    relative = path.relative_to(ROOT_DIR)
    return (
        relative.parent == Path("main_report")
        and path.name in AGGREGATE_REPORT_FILES
    )


def is_aggregate_generated_directory(path: Path) -> bool:
    """Identify summary tables and include lists rebuilt by report-inputs."""
    return path.relative_to(ROOT_DIR) == Path("main_report/generated")


def is_slurm_artifact(path: Path) -> bool:
    """Identify wrappers and scheduler logs generated by suite submission."""
    if path.name == "run_case_slurm.sh":
        return True
    return path.name.startswith("slurm-") and path.name.endswith(
        (".stdout", ".stderr", ".out", ".err")
    )


def is_generated_variant_directory(path: Path) -> bool:
    """Identify active verification variant trees regenerated by preprocessing.

    The verification-case contract reserves ``CASE*/variants/`` for generated
    run directories.  Scientific definitions, templates, and observations must
    live outside that tree so a clean checkout can reconstruct it.
    """
    relative = path.relative_to(ROOT_DIR)
    return (
        len(relative.parts) == 5
        and relative.parts[0:2] == ("cases", "Verification")
        and relative.parts[2] in {"unit_tests", "coupling_tests"}
        and relative.parts[3].startswith("CASE")
        and relative.parts[4] == "variants"
        and not path.is_symlink()
    )


def cleanup_inventory(
    prepare_run: bool = False,
) -> tuple[list[Path], list[Path], list[Path]]:
    """Return disposable files, runtime directories, and aux directories.

    Use one top-down walk so ``.git`` can be pruned before traversal. Active-case
    runtime contents are removed as directory units, so pruning them here avoids
    thousands of unnecessary metadata operations on shared filesystems.
    """
    artifacts: list[Path] = []
    runtime_directories: list[Path] = []
    auxiliary_directories: list[Path] = []

    for directory, child_directories, filenames in os.walk(ROOT_DIR, topdown=True):
        current = Path(directory)
        child_directories[:] = [
            name for name in child_directories if name not in {".git", "__legacy__"}
        ]

        is_active_case_runtime = (
            (
                current.name
                in (
                    CASE_RUNTIME_DIRECTORY_NAMES
                    | ({"figures"} if prepare_run else set())
                )
                and is_active_case_path(current)
                and not current.is_symlink()
            )
            or is_generated_variant_directory(current)
            or (
                prepare_run
                and is_aggregate_generated_directory(current)
                and not current.is_symlink()
            )
        )
        if is_active_case_runtime:
            runtime_directories.append(current)
            child_directories.clear()
            continue

        auxiliary_directories.extend(
            current / name
            for name in child_directories
            if name in {".aux", "__pycache__"}
        )

        for name in filenames:
            path = current / name
            if name == ".DS_Store" or path.suffix == ".pyc" or is_slurm_artifact(path):
                artifacts.append(path)
            elif is_generated_report_file(path, prepare_run=prepare_run):
                artifacts.append(path)
            elif prepare_run and is_aggregate_report_file(path):
                artifacts.append(path)
            elif is_report_path(path) and name.endswith(LATEX_SUFFIXES):
                artifacts.append(path)

    return (
        sorted(artifacts),
        sorted(runtime_directories),
        sorted(auxiliary_directories, reverse=True),
    )


def artifact_files(prepare_run: bool = False) -> list[Path]:
    """Compatibility helper used by tests and cleanup classification callers."""
    return cleanup_inventory(prepare_run=prepare_run)[0]


def disposable_runtime_entries(
    directory: Path, preserve_report_support: bool = True
) -> list[Path]:
    """List entries removable from one runtime directory."""
    return [
        entry
        for entry in directory.iterdir()
        if not (
            preserve_report_support
            and directory.name == "outputs"
            and entry.is_file()
            and entry.suffix.lower() in REPORT_SUPPORT_OUTPUT_SUFFIXES
        )
    ]


def empty_runtime_directories(
    directories: list[Path], apply: bool, preserve_report_support: bool = True
) -> int:
    """Clean runtime directories, optionally retaining report-supporting JSON."""
    cleaned = 0
    for directory in directories:
        entries = disposable_runtime_entries(
            directory, preserve_report_support=preserve_report_support
        )
        if not entries:
            continue
        cleaned += 1
        if not apply:
            continue
        for entry in entries:
            if entry.is_dir() and not entry.is_symlink():
                shutil.rmtree(entry)
            else:
                entry.unlink()
    return cleaned


def remove_empty_artifact_directories(directories: list[Path], apply: bool) -> int:
    removed = 0
    for directory in directories:
        if apply and directory.is_dir() and not any(directory.iterdir()):
            directory.rmdir()
            removed += 1
    return removed


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply", action="store_true", help="perform cleanup instead of previewing it"
    )
    parser.add_argument(
        "--prepare-run",
        action="store_true",
        help=(
            "also remove prior result JSON, figures, generated report inputs, "
            "and compiled case/suite reports before a new evaluation"
        ),
    )
    args = parser.parse_args()

    files, runtime_directories, auxiliary_directories = cleanup_inventory(
        prepare_run=args.prepare_run
    )
    directories = [path for path in GENERATED_DIRECTORIES if path.exists()]
    action = "REMOVE" if args.apply else "WOULD REMOVE"
    for path in files + directories:
        print(f"[{action}] {path.relative_to(ROOT_DIR)}")
    runtime_action = "CLEAN" if args.apply else "WOULD CLEAN"
    for path in runtime_directories:
        if disposable_runtime_entries(
            path, preserve_report_support=not args.prepare_run
        ):
            print(f"[{runtime_action}] {path.relative_to(ROOT_DIR)}")

    if args.apply:
        for path in files:
            path.unlink()
        for directory in directories:
            shutil.rmtree(directory)
        runtime_directory_count = empty_runtime_directories(
            runtime_directories,
            apply=True,
            preserve_report_support=not args.prepare_run,
        )
        empty_directory_count = remove_empty_artifact_directories(
            auxiliary_directories, apply=True
        )
    else:
        runtime_directory_count = empty_runtime_directories(
            runtime_directories,
            apply=False,
            preserve_report_support=not args.prepare_run,
        )
        empty_directory_count = 0

    runtime_result = "cleaned" if args.apply else "selected"
    print(
        f"[{'OK' if args.apply else 'PREVIEW'}] "
        f"{len(files)} files, {len(directories)} generated directories, and "
        f"{runtime_directory_count} case runtime directories {runtime_result}; "
        f"{empty_directory_count} empty artifact directories removed"
    )


if __name__ == "__main__":
    main()
