#!/usr/bin/env python3
"""Convert case-local metrics JSON into report-safe LaTeX macros."""

from __future__ import annotations

from report_language import report_text

import json
from pathlib import Path

CASE_DIR = Path(__file__).resolve().parents[1]
METRICS_PATH = CASE_DIR / "outputs" / "metrics.json"
MACROS_PATH = CASE_DIR / "report" / "metrics_macros.tex"


def latex(value: object) -> str:
    """Format and escape a scalar for a LaTeX table."""
    if value is None:
        return "--"
    if isinstance(value, float):
        text = f"{value:.6g}"
    else:
        text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "_": r"\_",
        "#": r"\#",
        "$": r"\$",
        "{": r"\{",
        "}": r"\}",
    }
    escaped = "".join(replacements.get(character, character) for character in text)
    return escaped.replace("<=", r"\ensuremath{\le}").replace(">=", r"\ensuremath{\ge}")


def main() -> None:
    if METRICS_PATH.exists():
        payload = json.loads(METRICS_PATH.read_text(encoding="utf-8"))
    else:
        payload = {
            "overall_status": "NOT EVALUABLE",
            "metrics": [],
            "reason": "outputs/metrics.json does not exist",
        }

    metrics = payload.get("metrics", [])
    status = str(payload.get("overall_status", "NOT EVALUABLE"))
    if status in {"NOT RUN", "INCOMPLETE", "BLOCKED"}:
        status = "NOT EVALUABLE"

    rows = []
    for metric in metrics:
        expected = metric.get("expected")
        tolerance = metric.get("tolerance")
        expected_text = latex(expected)
        if tolerance:
            expected_text += " (" + latex(tolerance) + ")"
        rows.append(
            f"{latex(metric.get('name', 'unnamed metric'))} & "
            f"{expected_text} & {latex(metric.get('calculated'))} "
            f"{latex(metric.get('units', ''))} & "
            f"{latex(metric.get('status', 'NOT EVALUABLE'))} \\\\"
        )

    if not rows:
        reason = latex(payload.get("reason", "No calculated metrics are available"))
        rows = [f"{reason} & -- & -- & NOT EVALUABLE \\\\"]

    variants = payload.get("variants")
    variant_count = len(variants) if isinstance(variants, list) else int(payload.get("required_outputs_complete", False))
    passing = sum(metric.get("status") == "PASS" for metric in metrics)
    body = [
        "% Generated by scripts/metrics_to_macro.py; do not edit by hand.",
        rf"\newcommand{{\VerificationStatus}}{{{latex(status)}}}",
        rf"\newcommand{{\VariantCount}}{{{variant_count}}}",
        rf"\newcommand{{\MetricCount}}{{{len(metrics)}}}",
        rf"\newcommand{{\PassingMetricCount}}{{{passing}}}",
        "\\newcommand{\\MetricRows}{%",
        *rows,
        "}",
        "",
    ]
    MACROS_PATH.parent.mkdir(parents=True, exist_ok=True)
    MACROS_PATH.write_text(report_text("\n".join(body)), encoding="utf-8")
    print(f"[OK] wrote {MACROS_PATH}")


if __name__ == "__main__":
    main()
