#!/usr/bin/env python3
"""Adapt the original ELMFIRE Guide harness to repository-native cases."""

from __future__ import annotations

from report_language import polish_figure, report_text

from dataclasses import replace
import importlib.util
import json
import os
from pathlib import Path
import re
import shutil

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


COMMON_DIR = Path(__file__).resolve().parent
GUIDE_MODULE_PATH = COMMON_DIR / "guide_verification.py"


def _load_guide_module():
    spec = importlib.util.spec_from_file_location("guide_verification", GUIDE_MODULE_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load GUIDE implementation from {GUIDE_MODULE_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


GUIDE = _load_guide_module()
GUIDE_CASES = {case.name: case for case in GUIDE.CASES}


def read_variants(case_dir: Path):
    """Read label, local configuration path, and original GUIDE case identity."""
    variants = []
    manifest = case_dir / "scripts" / "variants.tsv"
    for raw in manifest.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        label, config_rel, guide_name = raw.split("\t")
        variants.append((label, Path(config_rel), guide_name))
    if not variants:
        raise ValueError(f"No variants declared in {manifest}")
    return variants


def materialize_variant_namelist(
    case_dir: Path, label: str, config_rel: Path
) -> Path:
    """Create a generated variant namelist from case-local source material.

    The root ``elmfire.data.in`` remains the default source.  A scientifically
    distinct variant may instead provide ``scripts/namelists/<label>.in``.
    Nothing below ``variants/`` is treated as source material.
    """
    config_path = case_dir / config_rel
    if config_path == case_dir / "elmfire.data.in":
        if not config_path.is_file():
            raise FileNotFoundError(config_path)
        return config_path

    template = case_dir / "scripts" / "namelists" / f"{label}.in"
    source = template if template.is_file() else case_dir / "elmfire.data.in"
    if not source.is_file():
        raise FileNotFoundError(
            f"No source namelist for {label}: expected {template} or "
            f"{case_dir / 'elmfire.data.in'}"
        )
    config_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, config_path)
    return config_path


def generate_inputs(case_dir: Path) -> None:
    """Generate deterministic GUIDE rasters next to each local namelist."""
    for label, config_rel, guide_name in read_variants(case_dir):
        config_path = materialize_variant_namelist(case_dir, label, config_rel)
        guide_case = GUIDE_CASES[guide_name]
        GUIDE.generate_case_inputs(config_path.parent, config_path, guide_case)
        print(f"[OK] {label}: generated inputs for {guide_name}")


def _latex_escape(value) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(char, char) for char in text)


def _metric_key(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "", value)


def _variant_status(rows, has_outputs: bool, quantitative: bool) -> str:
    if not has_outputs:
        return "NOT RUN"
    decisions = [row["match"] for row in rows if row["match"] is not None]
    if not quantitative:
        return "NOT EVALUABLE"
    if not decisions:
        return "NOT EVALUABLE"
    return "PASS" if all(decisions) else "FAIL"


def _overall_status(statuses) -> str:
    if any(status == "FAIL" for status in statuses):
        return "FAIL"
    if statuses and all(status == "PASS" for status in statuses):
        return "PASS"
    if statuses and all(status == "NOT RUN" for status in statuses):
        return "NOT EVALUABLE"
    return "NOT EVALUABLE"


def _has_simulation_outputs(output_dir: Path) -> bool:
    if not output_dir.is_dir():
        return False
    ignored = {"metrics.json"}
    return any(path.is_file() and path.name not in ignored for path in output_dir.rglob("*"))


def _write_metrics_macros(report_dir: Path, payload: dict) -> None:
    lines = [
        "% Auto-generated by scripts/postprocess.py",
        rf"\newcommand{{\VerificationStatus}}{{{_latex_escape(payload['overall_status'])}}}",
        rf"\newcommand{{\VariantCount}}{{{len(payload['variants'])}}}",
        rf"\newcommand{{\MetricCount}}{{{payload['metric_count']}}}",
        rf"\newcommand{{\PassingMetricCount}}{{{payload['passing_metric_count']}}}",
    ]
    for variant in payload["variants"]:
        prefix = _metric_key(variant["label"])
        lines.append(
            rf"\expandafter\def\csname VariantStatus{prefix}\endcsname"
            rf"{{{_latex_escape(variant['status'])}}}"
        )
    metric_rows = []
    for variant in payload["variants"]:
        for metric in variant["metrics"]:
            target = "--" if metric["target"] is None else f"{metric['target']:.6g}"
            measured = "--" if metric["measured"] is None else f"{metric['measured']:.6g}"
            units = metric["units"] or "--"
            metric_rows.append(
                "{} / {} & {} {} & {} {} & {} \\\\".format(
                    _latex_escape(variant["label"]),
                    _latex_escape(metric["name"]),
                    _latex_escape(target),
                    _latex_escape(units),
                    _latex_escape(measured),
                    _latex_escape(units),
                    _latex_escape(metric["status"]),
                )
            )
    if not metric_rows:
        metric_rows.append(r"No required metrics & -- & -- & NOT EVALUABLE \\")
    lines.append(r"\newcommand{\MetricRows}{%")
    lines.extend(metric_rows)
    lines.append("}")
    (report_dir / "metrics_macros.tex").write_text(report_text("\n".join(lines) + "\n"), encoding="utf-8")


def _write_summary_figure(fig_path: Path, payload: dict) -> None:
    rows = [
        (variant["label"], metric)
        for variant in payload["variants"]
        for metric in variant["metrics"]
    ]
    height = max(3.0, 0.42 * max(1, len(rows)) + 1.6)
    fig, ax = plt.subplots(figsize=(8.2, height))
    ax.axis("off")
    ax.set_title(
        f"{payload['case_title']} - {payload['overall_status']}",
        fontsize=12,
        fontweight="bold",
        pad=14,
    )
    if rows:
        table_rows = []
        for label, metric in rows:
            target = "-" if metric["target"] is None else f"{metric['target']:.6g}"
            measured = "-" if metric["measured"] is None else f"{metric['measured']:.6g}"
            decision = metric["status"]
            table_rows.append([label, metric["name"], target, measured, decision])
        table = ax.table(
            cellText=table_rows,
            colLabels=["Condition", "Metric", "Target", "Measured", "Status"],
            cellLoc="left",
            colLoc="left",
            loc="center",
        )
        table.auto_set_font_size(False)
        table.set_fontsize(8)
        table.scale(1.0, 1.35)
    else:
        ax.text(0.5, 0.5, "No metrics are available.", ha="center", va="center")
    fig.tight_layout()
    polish_figure(fig)
    fig.savefig(fig_path, format="pdf", bbox_inches="tight")
    plt.close(fig)


def _write_whole_domain_figure(case_dir: Path, figure_dir: Path, variants) -> None:
    """Plot one complete case-local ELMFIRE raster as spatial evidence."""
    import rasterio

    priorities = (
        "time_of_arrival_*.tif",
        "phi_*.tif",
        "vs_*.tif",
        "crown_fire_*.tif",
    )
    selected = None
    selected_label = None
    for variant in variants:
        variant_dir = (case_dir / variant["configuration"]).parent
        output_dir = variant_dir / "outputs"
        for pattern in priorities:
            matches = sorted(output_dir.glob(pattern))
            if matches:
                selected = matches[-1]
                selected_label = variant["label"]
                break
        if selected is not None:
            break
    if selected is None:
        return

    with rasterio.open(selected) as src:
        data = src.read(1, masked=True).astype(float)
        bounds = src.bounds
        crs = src.crs
    fig, ax = plt.subplots(figsize=(7.0, 5.5))
    image = ax.imshow(
        data,
        extent=(bounds.left, bounds.right, bounds.bottom, bounds.top),
        origin="upper",
        cmap="viridis",
    )
    ax.set(
        xlabel="Easting (m)",
        ylabel="Northing (m)",
        title=f"{case_dir.name}: whole-domain simulated field",
    )
    fig.colorbar(image, ax=ax, label=("Fire arrival time (s)" if selected.name.startswith("time_of_arrival_") else "Simulated field (units described in caption)"))
    ax.text(
        0.01,
        0.01,
        f"Coordinate reference system: {crs}",
        transform=ax.transAxes,
        fontsize=7,
        bbox={"facecolor": "white", "alpha": 0.75, "edgecolor": "none"},
    )
    fig.tight_layout()
    polish_figure(fig)
    fig.savefig(figure_dir / "whole_domain_result.pdf", format="pdf", bbox_inches="tight")
    plt.close(fig)


def postprocess(case_dir: Path, case_id: str, case_title: str) -> dict:
    """Extract GUIDE metrics, write JSON/macros, and create a PDF summary."""
    output_dir = case_dir / "outputs"
    figure_dir = case_dir / "figures"
    report_dir = case_dir / "report"
    output_dir.mkdir(parents=True, exist_ok=True)
    figure_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    variants = []
    all_statuses = []
    metric_count = 0
    passing_count = 0
    for label, config_rel, guide_name in read_variants(case_dir):
        config_path = case_dir / config_rel
        variant_dir = config_path.parent
        variant_output = variant_dir / "outputs"
        original = GUIDE_CASES[guide_name]
        local_case = replace(original, data_rel=config_path.name)
        has_outputs = _has_simulation_outputs(variant_output)
        measured = {}
        if has_outputs:
            measured = GUIDE.METRICS[local_case.metric](str(variant_output), local_case)
        rows = GUIDE.evaluate_case(local_case, measured)
        status = _variant_status(rows, has_outputs, local_case.quantitative)
        all_statuses.append(status)
        metrics = []
        for row in rows:
            if row["match"] is True:
                decision = "PASS"
                passing_count += 1
            elif row["match"] is False:
                decision = "FAIL"
            elif not has_outputs:
                decision = "NOT RUN"
            else:
                decision = "NOT EVALUABLE"
            metric_count += 1
            metrics.append(
                {
                    "name": row["metric"],
                    "target": row["target"],
                    "measured": row["measured"],
                    "percent_error": row["pct_error"],
                    "units": row["units"],
                    "status": decision,
                }
            )
        variants.append(
            {
                "label": label,
                "guide_case": guide_name,
                "configuration": config_rel.as_posix(),
                "status": status,
                "metrics": metrics,
            }
        )

    payload = {
        "case_id": case_id,
        "case_title": case_title,
        "overall_status": _overall_status(all_statuses),
        "workflow_status": (
            "NOT RUN"
            if all_statuses and all(status == "NOT RUN" for status in all_statuses)
            else "INCOMPLETE"
            if any(status == "NOT RUN" for status in all_statuses)
            else "COMPLETE"
        ),
        "metric_count": metric_count,
        "passing_metric_count": passing_count,
        "variants": variants,
        "source": "ELMFIRE Guide verification section",
    }
    (output_dir / "metrics.json").write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8"
    )
    _write_metrics_macros(report_dir, payload)
    _write_summary_figure(figure_dir / "verification_summary.pdf", payload)
    _write_whole_domain_figure(case_dir, figure_dir, variants)
    return payload
