# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: available_polygons.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'available_polygons.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61vailable_polygons.proto\"E\n\x07Request\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\t\x12\x0c\n\x04list\x18\x03 \x01(\t\x12\x10\n\x08\x66irename\x18\x04 \x01(\t\"#\n\x05Reply\x12\x1a\n\x12\x61vailable_polygons\x18\x01 \x01(\t26\n\x11\x41vailablePolygons\x12!\n\x0bGetPolygons\x12\x08.Request\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'available_polygons_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=28
  _globals['_REQUEST']._serialized_end=97
  _globals['_REPLY']._serialized_start=99
  _globals['_REPLY']._serialized_end=134
  _globals['_AVAILABLEPOLYGONS']._serialized_start=136
  _globals['_AVAILABLEPOLYGONS']._serialized_end=190
# @@protoc_insertion_point(module_scope)
