# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import available_polygons_pb2 as available__polygons__pb2


class AvailablePolygonsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPolygons = channel.unary_unary(
                '/AvailablePolygons/GetPolygons',
                request_serializer=available__polygons__pb2.Request.SerializeToString,
                response_deserializer=available__polygons__pb2.Reply.FromString,
                )


class AvailablePolygonsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPolygons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvailablePolygonsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPolygons': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolygons,
                    request_deserializer=available__polygons__pb2.Request.FromString,
                    response_serializer=available__polygons__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AvailablePolygons', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AvailablePolygons(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPolygons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AvailablePolygons/GetPolygons',
            available__polygons__pb2.Request.SerializeToString,
            available__polygons__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
