# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: elmfire.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'elmfire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\relmfire.proto\"\xbf\x03\n\x07Request\x12\x10\n\x08\x66irename\x18\x01 \x01(\t\x12\x1b\n\x13initialization_type\x18\x02 \x01(\t\x12\x15\n\rignition_time\x18\x03 \x01(\t\x12\x1d\n\x15\x61\x63tive_fire_timestamp\x18\x04 \x01(\t\x12 \n\x18\x61lready_burned_timestamp\x18\x05 \x01(\t\x12\x14\n\x0cignition_lon\x18\x06 \x01(\x02\x12\x14\n\x0cignition_lat\x18\x07 \x01(\x02\x12\x12\n\ncenter_lon\x18\x08 \x01(\x02\x12\x12\n\ncenter_lat\x18\t \x01(\x02\x12\x13\n\x0bwest_buffer\x18\n \x01(\x02\x12\x14\n\x0csouth_buffer\x18\x0b \x01(\x02\x12\x13\n\x0b\x65\x61st_buffer\x18\x0c \x01(\x02\x12\x14\n\x0cnorth_buffer\x18\r \x01(\x02\x12\x1c\n\x14num_ensemble_members\x18\x0e \x01(\x05\x12\x17\n\x0fignition_radius\x18\x0f \x01(\x02\x12\x11\n\trun_hours\x18\x10 \x01(\x05\x12\x13\n\x0b\x66uel_source\x18\x11 \x01(\t\x12\x14\n\x0c\x66uel_version\x18\x12 \x01(\t\x12\x0e\n\x06outdir\x18\x13 \x01(\t\"E\n\x05Reply\x12\x16\n\x0estatus_message\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x0f\n\x07\x66ileloc\x18\x03 \x01(\t2+\n\x07\x45LMFIRE\x12 \n\nRunELMFIRE\x12\x08.Request\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'elmfire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=18
  _globals['_REQUEST']._serialized_end=465
  _globals['_REPLY']._serialized_start=467
  _globals['_REPLY']._serialized_end=536
  _globals['_ELMFIRE']._serialized_start=538
  _globals['_ELMFIRE']._serialized_end=581
# @@protoc_insertion_point(module_scope)
