# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fuel_wx_ign_pb2 as fuel__wx__ign__pb2


class FuelWxIgnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDomainData = channel.unary_unary(
                '/FuelWxIgn/GetDomainData',
                request_serializer=fuel__wx__ign__pb2.Request.SerializeToString,
                response_deserializer=fuel__wx__ign__pb2.Reply.FromString,
                )


class FuelWxIgnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDomainData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FuelWxIgnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDomainData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDomainData,
                    request_deserializer=fuel__wx__ign__pb2.Request.FromString,
                    response_serializer=fuel__wx__ign__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FuelWxIgn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FuelWxIgn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDomainData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelWxIgn/GetDomainData',
            fuel__wx__ign__pb2.Request.SerializeToString,
            fuel__wx__ign__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
